name: tests/run-partial-tests.sh
run-name: tests/run-partial-tests.sh${{ github.event_name == 'workflow_dispatch' && ! inputs.full && format(' Dockerfile.{0} with {1}', inputs.os, inputs.docker) || ' all' }} @ ${{ inputs.runs-on == '' && 'ubuntu-24.04' || inputs.runs-on }}

on:
  schedule:
    - cron: '42 3 1,15 * *'
  workflow_dispatch:
    inputs:
      full:
        description: Full set of tests
        required: true
        type: boolean
        default: false
      os:
        description: OS / Dockerfile
        type: string
      docker:
        description: docker or podman
        type: choice
        options:
          - docker
          - podman
      runs-on:
        description: Host Ubuntu version
        type: choice
        options:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04

jobs:
  gen-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.dispatch-matrix.outputs.matrix }}${{ steps.default-matrix.outputs.matrix }}
    steps:
      - id: default-matrix
        run: |
          (
          echo -n "matrix={'os': [ 'fedora-rawhide', 'fedora-41', 'fedora-40', 'centos-9-stream', 'rocky-9', 'rocky-8', 'almalinux-9', 'almalinux-8' ], \
          'docker': [ 'docker', 'podman' ] "
          if [ -n "${{ secrets.REDHAT_ORG }}" -a -n "${{ secrets.REDHAT_ACTIVATIONKEY }}" ] ; then
            echo -n ", 'include': [ \
              { 'os': 'rhel-9', 'docker': 'podman' }, \
              { 'os': 'rhel-8', 'docker': 'podman' } \
              ]"
          fi
          echo "}" ) | tee -a $GITHUB_OUTPUT
        if: github.event_name != 'workflow_dispatch' || inputs.full
      - id: dispatch-matrix
        run: |
          echo "matrix={'os': [ '${{ inputs.os }}' ], 'docker': [ '${{ inputs.docker }}' ]}" | tee -a $GITHUB_OUTPUT
        if: github.event_name == 'workflow_dispatch' && ! inputs.full

  test:
    runs-on: ${{ inputs.runs-on || 'ubuntu-24.04' }}
    needs: [ gen-matrix ]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.gen-matrix.outputs.matrix) }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Install podman 4.*
        uses: ./.github/actions/install-podman-4
        if: matrix.docker == 'podman' && inputs.runs-on == 'ubuntu-22.04'
      - uses: ./.github/actions/docker-cgroups-ubuntu-22
        if: matrix.docker == 'docker'
      - name: For RHEL builds, use entitlements
        if: ${{ startsWith(matrix.os, 'rhel-') }}
        uses: ./.github/actions/podman-entitlement
        with:
          org: ${{ secrets.REDHAT_ORG }}
          activationkey: ${{ secrets.REDHAT_ACTIVATIONKEY }}
      - name: Run partial tests
        run: docker=${{ matrix.docker }} tests/run-partial-tests.sh Dockerfile.${{ matrix.os }}
