name: Test RHEL-based FreeIPA containers

on:
  schedule:
    - cron: '50 3 1,15 * *'
  workflow_dispatch:

jobs:
  test-subscription:
    # Workaround https://github.com/actions/runner/issues/1138
    name: Prerequisite for RHEL builds
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      has_rhel_subscriptions: ${{ steps.check.outputs.has_rhel_subscriptions }}
    steps:
      - id: check
        run: |
          if [ -n "${{ secrets.REDHAT_ORG }}" -a -n "${{ secrets.REDHAT_ACTIVATIONKEY }}" ] ; then
            echo "has_rhel_subscriptions=1" >> $GITHUB_OUTPUT
          fi

  build-test-rhel-podman:
    name: Build and test RHEL image
    runs-on: ubuntu-24.04-arm
    needs: [ test-subscription ]
    if: needs.test-subscription.outputs.has_rhel_subscriptions == 1
    strategy:
      fail-fast: false
      matrix:
        os: [ rhel-9, rhel-8 ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: For RHEL builds, use entitlements
        uses: ./.github/actions/podman-entitlement
        with:
          org: ${{ secrets.REDHAT_ORG }}
          activationkey: ${{ secrets.REDHAT_ACTIVATIONKEY }}
      - name: Build image
        run: podman build -t localhost/freeipa-server:${{ matrix.os }} -f Dockerfile.${{ matrix.os }} .
      - name: Run master
        run: docker=podman tests/run-master-and-replica.sh localhost/freeipa-server:${{ matrix.os }}

